# Generated by Django 5.0.6 on 2024-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='img/')),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('en_descuento', models.BooleanField(default=False)),
                ('en_restock', models.BooleanField(default=False)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=20)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.producto')),
            ],
        ),
    ]
