# Generated by Django 5.0.6 on 2024-06-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='calificacion',
            new_name='descuento',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='subscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_subs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
