# Generated by Django 5.0.6 on 2024-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Carreras', 'Carreras'), ('Simulación', 'Simulación'), ('Acción', 'Acción'), ('Horror', 'Horror'), ('Aventura', 'Aventura'), ('Supervivencia', 'Supervivencia'), ('Sandbox', 'Sandbox'), ('Estrategia', 'Estrategia'), ('Party', 'Party'), ('Deportes', 'Deportes')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
