# Generated by Django 5.0.6 on 2024-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_categoria_alter_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento_subs',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_arriendo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Ruta', 'Ruta'), ('Urbana', 'Urbana'), ('Montaña', 'Montaña'), ('Infantil', 'Infantil')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
